package colonyview

import (
	"strings"
	"testing"

	uv "github.com/charmbracelet/ultraviolet"

	"github.com/tamnd/ari/kernel/eval"
	"github.com/tamnd/ari/ui/parts"
	"github.com/tamnd/ari/ui/theme"
)

func TestMain(m *testing.M) { eval.Main(m) }

// three surveyors mid-fan-out: one awake and spending, one blocked on a
// Question it posted, one still dormant, plus a fourth that already finished.
var fanout = State{
	Ants: []Ant{
		{ID: "surveyor-1", Name: "surveyor-1", Status: Awake, Tokens: 4210},
		{ID: "surveyor-2", Name: "surveyor-2", Status: Blocked, Tokens: 1875,
			Question: "the shared library re-exports a symbol from a generated file; run go generate?"},
		{ID: "surveyor-3", Name: "surveyor-3", Status: Dormant, Tokens: 0},
		{ID: "consolidator", Name: "consolidator", Status: Done, Tokens: 980},
	},
}

func frame(st State, w, h int) string {
	v := New(theme.Dark())
	v.SetState(st)
	buf := uv.NewScreenBuffer(w, h)
	v.Draw(buf, uv.Rect(0, 0, w, h))
	return buf.String()
}

// TestListGolden pins the ant list: a blocked ant floats to the top with its
// Question inline, awake sits above dormant, and the finished ant settles to
// the bottom, each with its glyph, status, and token count.
func TestListGolden(t *testing.T) {
	eval.Golden(t, "list", frame(fanout, 48, 12))
}

// TestBlockedGolden gives the blocked frame its own golden because a blocked
// ant with an inline Question is the frame most likely to regress.
func TestBlockedGolden(t *testing.T) {
	st := State{Ants: []Ant{
		{ID: "surveyor-2", Name: "surveyor-2", Status: Blocked, Tokens: 1875,
			Question: "run go generate to resolve the re-exported symbol?"},
	}}
	eval.Golden(t, "blocked", frame(st, 48, 6))
}

// TestDrillGolden pins the read-only drill-in: the focused ant's sidechain
// rendered with the same message-part renderer the main chat uses, so a colony
// transcript looks like a session.
func TestDrillGolden(t *testing.T) {
	st := fanout
	st.Focused = "surveyor-1"
	st.Transcript = []parts.Part{
		{Kind: parts.KindText, Role: parts.RoleUser, Text: "Survey how the shared library re-exports its symbols."},
		{Kind: parts.KindReasoning, Role: parts.RoleAssistant, Text: "The re-export chains through a generated file."},
		{Kind: parts.KindText, Role: parts.RoleAssistant, Text: "The symbol is generated by `go generate` in the api package."},
	}
	eval.Golden(t, "drill", frame(st, 60, 16))
}

// TestListSortsBlockedFirstThenAwakeThenDormant proves the ordering the render
// depends on, independent of the golden bytes.
func TestListSortsBlockedFirstThenAwakeThenDormant(t *testing.T) {
	out := frame(fanout, 48, 12)
	blocked := strings.Index(out, "blocked")
	awake := strings.Index(out, "awake")
	dormant := strings.Index(out, "dormant")
	done := strings.Index(out, "done")
	ordered := blocked >= 0 && blocked < awake && awake < dormant && dormant < done
	if !ordered {
		t.Errorf("order wrong: blocked=%d awake=%d dormant=%d done=%d\n%s", blocked, awake, dormant, done, out)
	}
}

// TestTokensShownToTheToken proves the per-ant spend renders exactly, so what
// the user sees matches the ledger and a token regression is visible.
func TestTokensShownToTheToken(t *testing.T) {
	out := frame(fanout, 48, 12)
	for _, want := range []string{"4210 tok", "1875 tok", "980 tok"} {
		if !strings.Contains(out, want) {
			t.Errorf("list missing exact spend %q:\n%s", want, out)
		}
	}
}

// TestDrillShowsTranscriptNotList proves focusing an ant swaps the list for its
// transcript: the read-only header shows and the other ants' rows do not.
func TestDrillShowsTranscriptNotList(t *testing.T) {
	st := fanout
	st.Focused = "surveyor-1"
	st.Transcript = []parts.Part{{Kind: parts.KindText, Role: parts.RoleUser, Text: "go generate the api package"}}
	out := frame(st, 60, 16)
	if !strings.Contains(out, "read-only") {
		t.Errorf("drill-in missing the read-only header:\n%s", out)
	}
	if strings.Contains(out, "dormant") {
		t.Errorf("drill-in leaked the list:\n%s", out)
	}
}
